import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import styled from 'styled-components';

// @ts-ignore
// import sineWaveSvg from '../public/sine_wave.svg';
import GlobalStyles from '../lib/globalStyles';


const socialLinks = [
  {
    url: "https://github.com/chrisdfe",
    name: "github"
  },
  {
    url: "https://www.linkedin.com/in/chrisdfe/",
    name: "linkedin"
  },
  {
    url: "#",
    name: "mail",
    openInNewTab: false
  }
]
// const Squiggle = styled.div`
//   background: red;
//   height: 10px;
//   width: 100px;
//   // @ts-ignore
//   background: url("`${ sineWaveSvg.src }`");
// `;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>@chrisdfe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyles />

      <main>
        <div className="content">
          <div className="content-inner">
            <section className="section-chrisdfe">
              <h1>
                Christopher Ferris is a Front End Developer that lives and works in
                Seattle, WA.
              </h1>

              <ul className="social-links">
                {socialLinks.map(socialLink => (
                  <li>
                    <a
                      href={socialLink.url}
                      target={socialLink.openInNewTab !== false ? '_blank' : ''}
                    >
                      {socialLink.name}
                    </a>
                  </li>
                ))}
              </ul>
            </section>

            <section className="section-sweaterparrot">
              <h3>
                He also creates art under the moniker <a href="http://sweaterparrot.com/">sweaterparrot</a>.
              </h3>
            </section>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
